// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jgilliescommure/go-person/internal/biz"
	"github.com/jgilliescommure/go-person/internal/conf"
	"github.com/jgilliescommure/go-person/internal/data"
	"github.com/jgilliescommure/go-person/internal/server"
	"github.com/jgilliescommure/go-person/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	personRepo := data.NewPersonRepo(dataData, logger)
	personUsecase := biz.NewPersonUsecase(personRepo, logger)
	personService := service.NewPersonService(personUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, personService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
